# Cross-Lingual Multimodal Transfer Pipeline

Research question: does adding audio help cross-lingual transfer for laughter-associated humor prediction?

Experiment design in this notebook:

- Train on English text only, evaluate on held-out English plus French / Spanish / Hungarian text.
- Train on English text + audio, evaluate on held-out English plus French / Spanish / Hungarian text + audio.

In [1]:
%pip install -U torch transformers librosa soundfile scikit-learn pandas numpy tqdm accelerate

Collecting torch

  Downloading torch-2.12.0-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (31 kB)

Collecting transformers
  Downloading transformers-5.9.0-py3-none-any.whl.metadata (33 kB)
Collecting librosa

  Downloading librosa-0.11.0-py3-none-any.whl.metadata (8.7 kB)
Collecting soundfile
  Downloading soundfile-0.13.1-py2.py3-none-manylinux_2_28_x86_64.whl.metadata (16 kB)

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: pandas in /opt/conda/lib/python3.13/site-packages (2.3.3)

Collecting pandas
  Downloading pandas-3.0.3-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Requirement already satisfied: numpy in /opt/conda/lib/python3.13/site-packages (2.4.3)

Collecting numpy
  Downloading numpy-2.4.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.13/site-packages (4.67.3)

Collecting accelerate
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Collecting filelock (from torch)
  Downloading filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/conda/lib/python3.13/site-packages (from torch) (4.15.0)

Collecting setuptools<82 (from torch)
  Downloading setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch)

  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.13/site-packages (from torch) (3.1.6)
Collecting fsspec>=0.8.5 (from torch)
  Downloading fsspec-2026.4.0-py3-none-any.whl.metadata (10 kB)

Collecting cuda-toolkit==13.0.2 (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Downloading cuda_toolkit-13.0.2-py2.py3-none-any.whl.metadata (9.4 kB)
Collecting nvidia-cublas<=13.1.1.3,>=13.1.0.3 (from torch)
  Downloading nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)

Collecting cuda-bindings<14,>=13.0.3 (from torch)
  Downloading cuda_bindings-13.2.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.3 kB)
Collecting nvidia-cudnn-cu13==9.20.0.48 (from torch)
  Downloading nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cusparselt-cu13==0.8.1 (from torch)

  Downloading nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
Collecting nvidia-nccl-cu13==2.29.7 (from torch)
  Downloading nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvshmem-cu13==3.4.5 (from torch)
  Downloading nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)

Collecting triton==3.7.0 (from torch)
  Downloading triton-3.7.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime==13.0.96.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Downloading nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft==12.0.0.61.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Downloading nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)

Collecting nvidia-cufile==1.15.1.6.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Downloading nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti==13.0.85.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Downloading nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand==10.4.0.35.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)

  Downloading nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver==12.0.4.66.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Downloading nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse==12.6.3.3.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Downloading nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink==13.0.88.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)

  Downloading nvidia_nvjitlink-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-nvrtc==13.0.88.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Downloading nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvtx==13.0.85.* (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Downloading nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)

Collecting cuda-pathfinder~=1.1 (from cuda-bindings<14,>=13.0.3->torch)
  Downloading cuda_pathfinder-1.5.4-py3-none-any.whl.metadata (1.9 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Downloading huggingface_hub-1.16.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.13/site-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.13/site-packages (from transformers) (6.0.3)

Collecting regex>=2025.10.22 (from transformers)
  Downloading regex-2026.5.9-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)

Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typer (from transformers)
  Downloading typer-0.25.1-py3-none-any.whl.metadata (15 kB)

Collecting safetensors>=0.4.3 (from transformers)

  Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading hf_xet-1.5.0-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/conda/lib/python3.13/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: anyio in /opt/conda/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /opt/conda/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /opt/conda/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /opt/conda/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /opt/conda/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)

Collecting audioread>=2.1.9 (from librosa)
  Downloading audioread-3.1.0-py3-none-any.whl.metadata (9.0 kB)
Collecting numba>=0.51.0 (from librosa)

  Downloading numba-0.65.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.9 kB)

Collecting scipy>=1.6.0 (from librosa)
  Downloading scipy-1.17.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting joblib>=1.0 (from librosa)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: decorator>=4.3.0 in /opt/conda/lib/python3.13/site-packages (from librosa) (5.2.1)

Collecting pooch>=1.1 (from librosa)
  Downloading pooch-1.9.0-py3-none-any.whl.metadata (10 kB)
Collecting soxr>=0.3.2 (from librosa)
  Downloading soxr-1.1.0-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.8 kB)

Collecting lazy_loader>=0.1 (from librosa)
  Downloading lazy_loader-0.5-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: msgpack>=1.0 in /opt/conda/lib/python3.13/site-packages (from librosa) (1.1.2)
Collecting standard-aifc (from librosa)
  Downloading standard_aifc-3.13.0-py3-none-any.whl.metadata (969 bytes)

Collecting standard-sunau (from librosa)
  Downloading standard_sunau-3.13.0-py3-none-any.whl.metadata (914 bytes)
Requirement already satisfied: cffi>=1.0 in /opt/conda/lib/python3.13/site-packages (from soundfile) (2.0.0)

Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.13/site-packages (from accelerate) (7.2.2)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.13/site-packages (from cffi>=1.0->soundfile) (2.22)

Collecting llvmlite<0.48,>=0.47.0dev0 (from numba>=0.51.0->librosa)
  Downloading llvmlite-0.47.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: platformdirs>=2.5.0 in /opt/conda/lib/python3.13/site-packages (from pooch>=1.1->librosa) (4.5.1)
Requirement already satisfied: requests>=2.19.0 in /opt/conda/lib/python3.13/site-packages (from pooch>=1.1->librosa) (2.32.5)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.13/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.13/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.6.3)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)

  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: click>=8.2.1 in /opt/conda/lib/python3.13/site-packages (from typer->transformers) (8.3.3)
Collecting shellingham>=1.3.0 (from typer->transformers)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: rich>=13.8.0 in /opt/conda/lib/python3.13/site-packages (from typer->transformers) (15.0.0)
Collecting annotated-doc>=0.0.2 (from typer->transformers)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.13/site-packages (from rich>=13.8.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.13/site-packages (from rich>=13.8.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.13/site-packages (from jinja2->torch) (3.0.3)

Collecting standard-chunk (from standard-aifc->librosa)
  Downloading standard_chunk-3.13.0-py3-none-any.whl.metadata (860 bytes)
Collecting audioop-lts (from standard-aifc->librosa)
  Downloading audioop_lts-0.2.2-cp313-abi3-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (2.0 kB)
Downloading torch-2.12.0-cp313-cp313-manylinux_2_28_x86_64.whl (532.3 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/532.3 MB ? eta -:--:--

   ━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/532.3 MB 82.4 MB/s eta 0:00:07

   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.4/532.3 MB 132.6 MB/s eta 0:00:04

   ━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.5/532.3 MB 134.5 MB/s eta 0:00:04

   ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.9/532.3 MB 128.1 MB/s eta 0:00:04

   ━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.5/532.3 MB 130.6 MB/s eta 0:00:04

   ━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.0/532.3 MB 126.9 MB/s eta 0:00:03

   ━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━ 187.2/532.3 MB 133.6 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━ 206.6/532.3 MB 129.1 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━ 231.7/532.3 MB 130.1 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━ 245.4/532.3 MB 123.9 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━ 267.4/532.3 MB 121.8 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━ 278.9/532.3 MB 121.6 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━ 302.5/532.3 MB 114.9 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━ 316.7/532.3 MB 111.0 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 342.9/532.3 MB 108.9 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━ 382.7/532.3 MB 115.1 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━ 394.3/532.3 MB 112.2 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━ 394.8/532.3 MB 102.4 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━ 419.7/532.3 MB 101.5 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 454.0/532.3 MB 101.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 479.2/532.3 MB 103.0 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 514.9/532.3 MB 115.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 532.2/532.3 MB 120.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 532.3/532.3 MB 109.7 MB/s  0:00:04
Downloading cuda_toolkit-13.0.2-py2.py3-none-any.whl (2.4 kB)
Downloading nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl (366.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/366.2 MB ? eta -:--:--

   ━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/366.2 MB 62.8 MB/s eta 0:00:06

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/366.2 MB 124.4 MB/s eta 0:00:03

   ━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/366.2 MB 121.6 MB/s eta 0:00:03

   ━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.4/366.2 MB 82.7 MB/s eta 0:00:04

   ━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.9/366.2 MB 95.7 MB/s eta 0:00:03

   ━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.8/366.2 MB 90.2 MB/s eta 0:00:03

   ━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.3/366.2 MB 76.2 MB/s eta 0:00:04

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.3/366.2 MB 71.1 MB/s eta 0:00:04

   ━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/366.2 MB 79.5 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━ 180.1/366.2 MB 89.6 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━ 215.5/366.2 MB 97.5 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 241.2/366.2 MB 100.1 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 250.6/366.2 MB 99.9 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 251.1/366.2 MB 90.7 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━ 281.0/366.2 MB 94.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 329.0/366.2 MB 111.0 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 353.6/366.2 MB 107.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 358.9/366.2 MB 102.2 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 366.0/366.2 MB 105.7 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.2/366.2 MB 104.3 MB/s  0:00:03

Downloading nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl (170.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/170.1 MB ? eta -:--:--

   ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.7/170.1 MB 85.6 MB/s eta 0:00:02

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/170.1 MB 62.7 MB/s eta 0:00:03

   ━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/170.1 MB 72.3 MB/s eta 0:00:02

   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.3/170.1 MB 76.8 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 72.9/170.1 MB 72.5 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━ 131.3/170.1 MB 108.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 MB 117.9 MB/s  0:00:01
Downloading nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl (206.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/206.0 MB ? eta -:--:--

   ━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.4/206.0 MB 236.2 MB/s eta 0:00:01

   ━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.0/206.0 MB 158.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/206.0 MB 117.1 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━ 87.0/206.0 MB 108.3 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 140.5/206.0 MB 143.5 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 140.8/206.0 MB 125.0 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 185.3/206.0 MB 131.7 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.0/206.0 MB 131.6 MB/s  0:00:01
Downloading nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (60.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/60.4 MB ? eta -:--:--

   ━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/60.4 MB 110.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 40.4/60.4 MB 100.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 MB 125.9 MB/s  0:00:00
Downloading triton-3.7.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (201.5 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/201.5 MB ? eta -:--:--

   ━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/201.5 MB 52.1 MB/s eta 0:00:04

   ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.7/201.5 MB 94.0 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━ 80.0/201.5 MB 138.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━ 116.4/201.5 MB 157.0 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━ 116.9/201.5 MB 119.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━ 141.6/201.5 MB 130.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 149.9/201.5 MB 109.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━ 150.2/201.5 MB 99.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━ 170.4/201.5 MB 95.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 200.3/201.5 MB 100.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.5/201.5 MB 96.9 MB/s  0:00:02
Downloading cuda_bindings-13.2.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (6.1 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 180.7 MB/s  0:00:00
Downloading cuda_pathfinder-1.5.4-py3-none-any.whl (51 kB)
Downloading nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl (423.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/423.1 MB ? eta -:--:--

   ━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/423.1 MB 159.1 MB/s eta 0:00:03

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.5/423.1 MB 134.1 MB/s eta 0:00:03

   ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/423.1 MB 141.5 MB/s eta 0:00:03

   ━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/423.1 MB 118.6 MB/s eta 0:00:03

   ━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.6/423.1 MB 99.5 MB/s eta 0:00:04

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━ 142.9/423.1 MB 119.4 MB/s eta 0:00:03

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 186.9/423.1 MB 134.5 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━ 246.7/423.1 MB 153.8 MB/s eta 0:00:02

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 281.0/423.1 MB 165.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 283.4/423.1 MB 140.7 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━ 331.4/423.1 MB 154.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 370.9/423.1 MB 197.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 410.0/423.1 MB 193.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 410.3/423.1 MB 171.5 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 423.1/423.1 MB 160.5 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 MB 145.3 MB/s  0:00:03
Downloading nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/10.7 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 269.4 MB/s  0:00:00
Downloading nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (90.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/90.2 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 38.5/90.2 MB 193.8 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 81.8/90.2 MB 251.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 MB 158.5 MB/s  0:00:00
Downloading nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/2.2 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 343.1 MB/s  0:00:00
Downloading nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (214.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/214.1 MB ? eta -:--:--

   ━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.7/214.1 MB 202.5 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━ 85.7/214.1 MB 213.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━ 109.1/214.1 MB 189.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━ 133.7/214.1 MB 166.9 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 183.5/214.1 MB 183.0 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.1/214.1 MB 182.9 MB/s  0:00:01
Downloading nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 230.8 MB/s  0:00:00
Downloading nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl (59.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/59.5 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 42.7/59.5 MB 215.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 MB 197.7 MB/s  0:00:00

Downloading nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl (200.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/200.9 MB ? eta -:--:--

   ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.1/200.9 MB 210.4 MB/s eta 0:00:01

   ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/200.9 MB 156.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━ 88.3/200.9 MB 151.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 134.2/200.9 MB 167.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━ 174.1/200.9 MB 185.5 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.9/200.9 MB 164.9 MB/s  0:00:01
Downloading nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (145.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/145.9 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━ 64.0/145.9 MB 320.6 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━ 114.3/145.9 MB 309.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 123.7/145.9 MB 232.7 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 124.3/145.9 MB 163.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.9/145.9 MB 147.1 MB/s  0:00:00
Downloading nvidia_nvjitlink-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (40.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/40.7 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.7/40.7 MB 231.4 MB/s  0:00:00
Downloading nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (148 kB)
Downloading setuptools-81.0.0-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 402.0 MB/s  0:00:00
Downloading transformers-5.9.0-py3-none-any.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/10.8 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 184.2 MB/s  0:00:00
Downloading huggingface_hub-1.16.1-py3-none-any.whl (668 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/668.2 kB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 668.2/668.2 kB 237.8 MB/s  0:00:00
Downloading hf_xet-1.5.0-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 372.3 MB/s  0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 277.5 MB/s  0:00:00

Downloading librosa-0.11.0-py3-none-any.whl (260 kB)
Downloading soundfile-0.13.1-py2.py3-none-manylinux_2_28_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 37.7 MB/s  0:00:00
Downloading scikit_learn-1.8.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/8.9 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 187.7 MB/s  0:00:00
Downloading pandas-3.0.3-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/10.9 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 209.7 MB/s  0:00:00
Downloading numpy-2.4.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/16.6 MB ? eta -:--:--

   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/16.6 MB 24.6 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 56.9 MB/s  0:00:00
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
Downloading audioread-3.1.0-py3-none-any.whl (23 kB)
Downloading filelock-3.29.0-py3-none-any.whl (39 kB)
Downloading fsspec-2026.4.0-py3-none-any.whl (203 kB)

Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading lazy_loader-0.5-py3-none-any.whl (8.0 kB)
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 555.9 MB/s  0:00:00
Downloading numba-0.65.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/3.8 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 118.8 MB/s  0:00:00
Downloading llvmlite-0.47.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/56.3 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━ 22.0/56.3 MB 188.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 37.5/56.3 MB 95.1 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━ 47.2/56.3 MB 79.3 MB/s eta 0:00:01

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 83.5 MB/s  0:00:00

Downloading pooch-1.9.0-py3-none-any.whl (67 kB)
Downloading regex-2026.5.9-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (801 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 801.3/801.3 kB 358.1 MB/s  0:00:00
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)

Downloading scipy-1.17.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/35.2 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 164.4 MB/s  0:00:00

Downloading soxr-1.1.0-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (240 kB)
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 419.0 MB/s  0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 298.4 MB/s  0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)

Downloading typer-0.25.1-py3-none-any.whl (58 kB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading standard_aifc-3.13.0-py3-none-any.whl (10 kB)
Downloading audioop_lts-0.2.2-cp313-abi3-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (85 kB)
Downloading standard_chunk-3.13.0-py3-none-any.whl (4.9 kB)
Downloading standard_sunau-3.13.0-py3-none-any.whl (7.4 kB)

Installing collected packages: standard-chunk, nvidia-cusparselt-cu13, mpmath, cuda-toolkit, triton, threadpoolctl, sympy, shellingham, setuptools, safetensors, regex, nvidia-nvtx, nvidia-nvshmem-cu13, nvidia-nvjitlink, nvidia-nccl-cu13, nvidia-curand, nvidia-cufile, nvidia-cuda-runtime, nvidia-cuda-nvrtc, nvidia-cuda-cupti, numpy, networkx, llvmlite, lazy_loader, joblib, hf-xet, fsspec, filelock, cuda-pathfinder, audioop-lts, annotated-doc, standard-sunau, standard-aifc, soxr, soundfile, scipy, pooch, pandas, nvidia-cusparse, nvidia-cufft, nvidia-cublas, numba, cuda-bindings, typer, scikit-learn, nvidia-cusolver, nvidia-cudnn-cu13, audioread, librosa, huggingface-hub, torch, tokenizers, transformers, accelerate

   ╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/54 [nvidia-cusparselt-cu13]

   ━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/54 [mpmath]

   ━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/54 [cuda-toolkit]

   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/54 [triton]

   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/54 [triton]

   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/54 [triton]

   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/54 [triton]

   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/54 [triton]

   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/54 [triton]

   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/54 [triton]

   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/54 [triton]

   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/54 [triton]

   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/54 [triton]

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

  Attempting uninstall: setuptools
    Found existing installation: setuptools 82.0.0
    Uninstalling setuptools-82.0.0:
   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/54 [sympy]

   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/54 [setuptools]

      Successfully uninstalled setuptools-82.0.0
   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/54 [setuptools]

   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/54 [setuptools]

   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/54 [setuptools]

   ━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/54 [nvidia-nvshmem-cu13]

   ━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/54 [nvidia-nvjitlink]

   ━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/54 [nvidia-nvjitlink]

   ━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/54 [nvidia-nccl-cu13]

   ━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/54 [nvidia-nccl-cu13]

   ━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/54 [nvidia-curand]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/54 [nvidia-cuda-nvrtc]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/54 [nvidia-cuda-nvrtc]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/54 [nvidia-cuda-nvrtc]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/54 [nvidia-cuda-nvrtc]

  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.3
   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/54 [nvidia-cuda-nvrtc]

    Uninstalling numpy-2.4.3:
   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/54 [nvidia-cuda-nvrtc]

   ━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━ 20/54 [numpy]

      Successfully uninstalled numpy-2.4.3
   ━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━ 20/54 [numpy]

   ━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━ 20/54 [numpy]

   ━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━ 20/54 [numpy]

   ━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━ 20/54 [numpy]

   ━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━ 20/54 [numpy]

   ━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━ 20/54 [numpy]

   ━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━ 20/54 [numpy]

   ━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━ 21/54 [networkx]

   ━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━ 21/54 [networkx]

   ━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━ 21/54 [networkx]

   ━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━ 22/54 [llvmlite]

   ━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━ 22/54 [llvmlite]

   ━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━ 22/54 [llvmlite]

   ━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━ 24/54 [joblib]

   ━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━ 26/54 [fsspec]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 35/54 [scipy]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 35/54 [scipy]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 35/54 [scipy]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 35/54 [scipy]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 35/54 [scipy]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 35/54 [scipy]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 35/54 [scipy]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 35/54 [scipy]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 35/54 [scipy]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 35/54 [scipy]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 35/54 [scipy]

  Attempting uninstall: pandas
    Found existing installation: pandas 2.3.3
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

    Uninstalling pandas-2.3.3:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

      Successfully uninstalled pandas-2.3.3
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 37/54 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━ 38/54 [nvidia-cusparse]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 39/54 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 39/54 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 39/54 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 39/54 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 39/54 [nvidia-cufft]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━ 40/54 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━ 40/54 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━ 40/54 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━ 40/54 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━ 40/54 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━ 40/54 [nvidia-cublas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 41/54 [numba]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 41/54 [numba]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 41/54 [numba]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 41/54 [numba]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 41/54 [numba]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 41/54 [numba]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━ 42/54 [cuda-bindings]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 44/54 [scikit-learn]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 44/54 [scikit-learn]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 44/54 [scikit-learn]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 44/54 [scikit-learn]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 44/54 [scikit-learn]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 44/54 [scikit-learn]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━ 45/54 [nvidia-cusolver]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━ 45/54 [nvidia-cusolver]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 46/54 [nvidia-cudnn-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 46/54 [nvidia-cudnn-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 46/54 [nvidia-cudnn-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 46/54 [nvidia-cudnn-cu13]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 49/54 [huggingface-hub]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 50/54 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 51/54 [tokenizers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 52/54 [transformers]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54/54 [accelerate]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyspark-client 4.1.1 requires googleapis-common-protos>=1.71.0, which is not installed.
pyspark-client 4.1.1 requires grpcio>=1.76.0, which is not installed.
pyspark-client 4.1.1 requires grpcio-status>=1.76.0, which is not installed.
pyspark-client 4.1.1 requires pyarrow>=15.0.0, which is not installed.
pyspark-connect 4.1.1 requires googleapis-common-protos>=1.71.0, which is not installed.
pyspark-connect 4.1.1 requires grpcio>=1.76.0, which is not installed.
pyspark-connect 4.1.1 requires grpcio-status>=1.76.0, which is not installed.
pyspark-connect 4.1.1 requires pyarrow>=11.0.0, which is not installed.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.3 which is incompatible.
Successfully installed accelerate-1.13.0 annotated-doc-0.0.4 audioop-lts-0.2.2 audioread-3.1.0 cuda-bindings-13.2.0 cuda-pathfinder-1.5.4 cuda-toolkit-13.0.2 filelock-3.29.0 fsspec-2026.4.0 hf-xet-1.5.0 huggingface-hub-1.16.1 joblib-1.5.3 lazy_loader-0.5 librosa-0.11.0 llvmlite-0.47.0 mpmath-1.3.0 networkx-3.6.1 numba-0.65.1 numpy-2.4.6 nvidia-cublas-13.1.1.3 nvidia-cuda-cupti-13.0.85 nvidia-cuda-nvrtc-13.0.88 nvidia-cuda-runtime-13.0.96 nvidia-cudnn-cu13-9.20.0.48 nvidia-cufft-12.0.0.61 nvidia-cufile-1.15.1.6 nvidia-curand-10.4.0.35 nvidia-cusolver-12.0.4.66 nvidia-cusparse-12.6.3.3 nvidia-cusparselt-cu13-0.8.1 nvidia-nccl-cu13-2.29.7 nvidia-nvjitlink-13.0.88 nvidia-nvshmem-cu13-3.4.5 nvidia-nvtx-13.0.85 pandas-3.0.3 pooch-1.9.0 regex-2026.5.9 safetensors-0.7.0 scikit-learn-1.8.0 scipy-1.17.1 setuptools-81.0.0 shellingham-1.5.4 soundfile-0.13.1 soxr-1.1.0 standard-aifc-3.13.0 standard-chunk-3.13.0 standard-sunau-3.13.0 sympy-1.14.0 threadpoolctl-3.6.0 tokenizers-0.22.2 torch-2.12.0 transformers-5.9.0 triton-3.7.0 typer-0.25.1

Note: you may need to restart the kernel to use updated packages.

In [2]:
from pathlib import Path
import random

import numpy as np
import pandas as pd
import torch

from pipeline.config import PipelineConfig
from pipeline.embeddings import load_or_extract_features
from pipeline.experiment import build_crosslingual_dataset
from pipeline.laughter import AnnotationLaughterDetector
from pipeline.train import (
    evaluate_on_indices,
    metric_row,
    train_transfer_model,
    video_train_val_test_indices,
)

## Config

`RMSLaughterDetector` is only the temporary label module.

In [3]:
cfg = PipelineConfig(
    lang="en",
    # audio_root_name="dataset/audios/en",
    sample_limit=None,  # set to None for the full experiment
    random_seed=42,
    qwen_model_id="Qwen/Qwen3-0.6B",
    whisper_model_id="openai/whisper-large-v3-turbo",
    batch_size_embed_text=4,
    batch_size_train=16,
    epochs=8,
    fusion_hidden_dim=512,
    fusion_num_heads=8,
)

TRAIN_LANG = "en"
TEST_LANGS = ["fr","hu"] # "es", 
ALL_LANGS = [TRAIN_LANG] + TEST_LANGS

AUDIO_ROOTS = {
    "en": cfg.project_root / "cleaned-data" / "en",
    "fr": cfg.project_root / "cleaned-data" / "fr",
    "es": cfg.project_root / "cleaned-data" / "es",
    "hu": cfg.project_root / "cleaned-data" / "hu",
}

SAMPLE_LIMITS = {lang: cfg.sample_limit for lang in ALL_LANGS}

MODEL_MODES = {
    "text_only": "text",
    "text_audio_concat": "concat",
    "text_audio_cross_attention": "cross_attention",
}

random.seed(cfg.random_seed)
np.random.seed(cfg.random_seed)
torch.manual_seed(cfg.random_seed)

print("device:", cfg.device)
print("artifacts:", cfg.artifact_dir)
for lang, root in AUDIO_ROOTS.items():
    print(lang, "transcripts=", cfg.project_root / "asr-output" / lang, "audio=", root)

device: cuda
artifacts: /work/ccs2-train/pipeline_artifacts
en transcripts= /work/ccs2-train/asr-output/en audio= /work/ccs2-train/cleaned-data/en
fr transcripts= /work/ccs2-train/asr-output/fr audio= /work/ccs2-train/cleaned-data/fr
es transcripts= /work/ccs2-train/asr-output/es audio= /work/ccs2-train/cleaned-data/es
hu transcripts= /work/ccs2-train/asr-output/hu audio= /work/ccs2-train/cleaned-data/hu

## Build Cross-Lingual Dataset

In [4]:
laughter_detector = AnnotationLaughterDetector(cfg)
matched_by_lang, segments_df = build_crosslingual_dataset(
    ALL_LANGS,
    AUDIO_ROOTS,
    laughter_detector,
    cfg,
    sample_limits=SAMPLE_LIMITS,
)

segments_csv = cfg.artifact_dir / "crosslingual_segment_dataset.csv"
segments_df.to_csv(segments_csv, index=False)

print("saved:", segments_csv)
print("segments:", segments_df.shape)
print("matched videos by language:")
for lang, matched in matched_by_lang.items():
    print(lang, len(matched))
print("segments by language and label:")
print(pd.crosstab(segments_df["lang"], segments_df["label"]))
segments_df.head()

building segments:   0%|          | 0/158 [00:00<?, ?it/s]

building segments:   0%|          | 0/99 [00:00<?, ?it/s]

building segments:   0%|          | 0/349 [00:00<?, ?it/s]

saved: /work/ccs2-train/pipeline_artifacts/crosslingual_segment_dataset.csv
segments: (74277, 14)
matched videos by language:
en 158
fr 99
hu 349
segments by language and label:
label      0     1
lang
en     22944  4300
fr     16665  7856
hu     14919  7593

,lang,sample_idx,segment_id,title,json_path,foreground_path,crowd_path,start,end,duration,text,label,crowd_score,num_laughter_intervals_in_video
0,en,0,0,-dr7k9ybQdQ,/work/ccs2-train/asr-output/en/-dr7k9ybQdQ.json,/work/ccs2-train/cleaned-data/en/-dr7k9ybQdQ F...,/work/ccs2-train/cleaned-data/en/-dr7k9ybQdQ F...,0.00,2.18,2.18,And that's how you give a pope a tattoo.,0,0.0,19
1,en,0,1,-dr7k9ybQdQ,/work/ccs2-train/asr-output/en/-dr7k9ybQdQ.json,/work/ccs2-train/cleaned-data/en/-dr7k9ybQdQ F...,/work/ccs2-train/cleaned-data/en/-dr7k9ybQdQ F...,6.92,9.18,2.26,Now we're going to play a game entitled Living...,0,0.0,19
2,en,0,2,-dr7k9ybQdQ,/work/ccs2-train/asr-output/en/-dr7k9ybQdQ.json,/work/ccs2-train/cleaned-data/en/-dr7k9ybQdQ F...,/work/ccs2-train/cleaned-data/en/-dr7k9ybQdQ F...,9.32,11.00,1.68,"This game is for Ryan, Colin, and Wayne.",0,0.0,19
3,en,0,3,-dr7k9ybQdQ,/work/ccs2-train/asr-output/en/-dr7k9ybQdQ.json,/work/ccs2-train/cleaned-data/en/-dr7k9ybQdQ F...,/work/ccs2-train/cleaned-data/en/-dr7k9ybQdQ F...,11.24,12.56,1.32,So come on down.,0,0.0,19
4,en,0,4,-dr7k9ybQdQ,/work/ccs2-train/asr-output/en/-dr7k9ybQdQ.json,/work/ccs2-train/cleaned-data/en/-dr7k9ybQdQ F...,/work/ccs2-train/cleaned-data/en/-dr7k9ybQdQ F...,13.22,14.72,1.50,You are going to need some help in this game.,0,0.0,19

## English Train/Validation Split

Only English is used for training. English has a held-out in-language test split; French, Spanish, and Hungarian are held out as cross-lingual test languages.

In [5]:
train_idx, val_idx, en_test_idx = video_train_val_test_indices(
    segments_df,
    TRAIN_LANG,
    cfg.random_seed,
    val_size=0.15,
    test_size=0.15,
)

test_indices = {TRAIN_LANG: en_test_idx}
test_indices.update({
    lang: segments_df.index[segments_df["lang"] == lang].to_numpy()
    for lang in TEST_LANGS
})

print("train segments:", len(train_idx), "val segments:", len(val_idx), "en test segments:", len(en_test_idx))
for lang, idx in test_indices.items():
    print(f"test {lang}:", len(idx))

train segments: 18799 val segments: 4811 en test segments: 3634
test en: 3634
test fr: 24521
test hu: 22512

## Extract Or Load Features

The cache checks row identity, so changing language/sample selection will trigger recomputation automatically.

In [6]:
text_hidden, audio_hidden, y = load_or_extract_features(segments_df, cfg, force_recompute=False)

print("num segments:", len(y))
print("text dim:", text_hidden[0].shape[-1], "example text shape:", text_hidden[0].shape)
print("audio dim:", audio_hidden[0].shape[-1], "example audio shape:", audio_hidden[0].shape)
print("labels:", y.shape, np.bincount(y))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/726 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/9.73k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/1.50G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/311 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Qwen3 text sequence embeddings:   0%|          | 0/18570 [00:00<?, ?it/s]

preprocessor_config.json:   0%|          | 0.00/340 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.26k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/283k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.71M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/494k [00:00<?, ?B/s]

normalizer.json:   0%|          | 0.00/52.7k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.19k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.62G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/587 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/3.77k [00:00<?, ?B/s]

Whisper audio sequence embeddings:   0%|          | 0/74277 [00:00<?, ?it/s]

saved: /work/ccs2-train/pipeline_artifacts/crosslingual_sequence_features_qwen3_whisper.npz
num segments: 74277
text dim: 1024 example text shape: (11, 1024)
audio dim: 1280 example audio shape: (188, 1280)
labels: (74277,) [54528 19749]

## Train On English, Test Cross-Lingually

In [7]:
results = []
histories = {}
trained_models = {}

for model_name, mode in MODEL_MODES.items():
    print("\n===", model_name, "===")
    model, history = train_transfer_model(mode, text_hidden, audio_hidden, y, train_idx, val_idx, cfg)
    trained_models[model_name] = model
    histories[model_name] = history

    for test_lang, indices in test_indices.items():
        metrics = evaluate_on_indices(model, text_hidden, audio_hidden, y, indices, cfg)
        results.append(metric_row(model_name, TRAIN_LANG, test_lang, metrics))

results_df = pd.DataFrame(results).sort_values(["test_lang", "model"])
results_path = cfg.artifact_dir / "crosslingual_transfer_results.csv"
results_df.to_csv(results_path, index=False)
print("saved:", results_path)
results_df

=== text_only ===

           text epoch 01 loss=0.6943 val_f1=0.2283

           text epoch 02 loss=0.6797 val_f1=0.2412

           text epoch 03 loss=0.6715 val_f1=0.2502

           text epoch 04 loss=0.6656 val_f1=0.2461

           text epoch 05 loss=0.6586 val_f1=0.2518

           text epoch 06 loss=0.6466 val_f1=0.2771

           text epoch 07 loss=0.6313 val_f1=0.2416

           text epoch 08 loss=0.6134 val_f1=0.2426

=== text_audio_concat ===

         concat epoch 01 loss=0.6903 val_f1=0.2408

         concat epoch 02 loss=0.6694 val_f1=0.2236

         concat epoch 03 loss=0.6571 val_f1=0.2221

         concat epoch 04 loss=0.6471 val_f1=0.2436

         concat epoch 05 loss=0.6349 val_f1=0.2402

         concat epoch 06 loss=0.6210 val_f1=0.2508

         concat epoch 07 loss=0.6018 val_f1=0.2350

         concat epoch 08 loss=0.5849 val_f1=0.2631

=== text_audio_cross_attention ===

cross_attention epoch 01 loss=0.6941 val_f1=0.2500

cross_attention epoch 02 loss=0.6688 val_f1=0.2407

cross_attention epoch 03 loss=0.6517 val_f1=0.2542

cross_attention epoch 04 loss=0.6322 val_f1=0.2342

cross_attention epoch 05 loss=0.5990 val_f1=0.2439

cross_attention epoch 06 loss=0.5609 val_f1=0.1985

cross_attention epoch 07 loss=0.5167 val_f1=0.2219

cross_attention epoch 08 loss=0.4751 val_f1=0.2263

saved: /work/ccs2-train/pipeline_artifacts/crosslingual_transfer_results.csv

,model,train_lang,test_lang,accuracy,precision_1,recall_1,f1_1
3,text_audio_concat,en,en,0.741882,0.322102,0.354599,0.337571
6,text_audio_cross_attention,en,en,0.733076,0.332200,0.434718,0.376607
0,text_only,en,en,0.747386,0.309375,0.293769,0.301370
4,text_audio_concat,en,fr,0.674483,0.472074,0.135565,0.210641
7,text_audio_cross_attention,en,fr,0.646140,0.439765,0.381492,0.408561
1,text_only,en,fr,0.668529,0.435728,0.117363,0.184918
5,text_audio_concat,en,hu,0.645167,0.441377,0.195838,0.271301
8,text_audio_cross_attention,en,hu,0.649476,0.463319,0.247860,0.322952
2,text_only,en,hu,0.640059,0.344891,0.074674,0.122767

## Reading The Result

The key comparison is within each test language:

```text
text_only vs text_audio_concat / text_audio_cross_attention
```

If text+audio improves F1 on held-out English and/or French, Spanish, or Hungarian relative to text-only, that supports the hypothesis that audio helps cross-lingual transfer.

## Replacing The Label Module

```python
class Standup4AILaughterDetector:
    def detect(self, row):
        return [(start_sec, end_sec), ...]
```

Replace:

```python
laughter_detector = AnnotationLaughterDetector(cfg)
```